version: '3'

services:
  nodejs:
    build: .
    container_name: my-nodejs-app
    expose:
      - '3030'
    networks:
      - my-network

  nginx:
    image: 'nginx:latest'
    container_name: my-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network

networks:
  my-network:
